### ISSUE TITLE
wrong protocol name on syncing example

### ISSUE THREAD

**Issue by plebhash** [altonen/litep2p#28]
https://github.com/altonen/litep2p/blob/a90764ecbf270a2dff6e0251f5a6464e4e8ed92f/examples/syncing.rs#L81

I believe this should be `"/notif/block-announce/1"`?

**Comment by altonen** [comment]
It doesn't matter. You can choose the name for your own protocols, basically anything that satisfies `AsRef<str>`

**Comment by altonen** [comment]
Fair enough. It's not a copy-paste error because the names are modeled after the protocols we have in Polkadot, with the addition of `/sync` prefix to denote that these are all "sub-protocols" of a collection of protocols that together make *the* syncing protocol.

But I'm indifferent about the naming so I'll rename them to be more consistent.
